Config = Config or {}

Config.DailyLimit = 1
-- Config.WeeklyContestLimit = 2 -- 1 contest per day.
Config.ScrubPrice = 12500
Config.SprayPrice = 5000
Config.GangSprayPrice = 10000

Config.Graffitis = {}
Config.NearbyGraffitis = {}

Config.Sprays = {
    ["bakker"] = {
        IsGang = false,
        IsBusiness = false,
        Name = "Bakker",
        Model = "fw_sprays_bakker",
        SprayColor = { 255, 255, 255 },
        BlipColor = 85,
    },
    ["flying_dragons"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Flying Dragons",
        Model = "fw_sprays_flying_dragons",
        SprayColor = { 255, 0, 0 },
        BlipColor = 6,
    },
    ["kings"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Kings",
        Model = "fw_sprays_kings",
        SprayColor = { 255, 255, 255 },
        BlipColor = 0,
    },
    ["los_aztecas"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Los Aztecas",
        Model = "fw_sprays_los_aztecas",
        SprayColor = { 93, 182, 229 },
        BlipColor = 18,
    },
    -- ["los_muertos_mc"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Los Muertos MC",
    --     Model = "fw_sprays_los_muertos",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 62,
    -- },
    ["lost_holland"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "The Lost Holland",
        Model = "fw_sprays_lost_holland",
        SprayColor = { 255, 255, 255 },
        BlipColor = 40,
    },
    -- ["marabunta_perrera"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Marabunta Perrera",
    --     Model = "fw_sprays_marabunta_perrera",
    --     SprayColor = { 0, 0, 255 },
    --     BlipColor = 38,
    -- },
    ["dark_wolves"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Dark Wolves MC",
        Model = "fw_sprays_dark_wolves",
        SprayColor = { 208, 201, 183 },
        BlipColor = 16,
    },
    -- ["ogs"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Original Gangsters",
    --     Model = "fw_sprays_ogs",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 20,
    -- },
    -- ["los_lobos"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Los Lobos",
    --     Model = "fw_sprays_los_lobos",
    --     SprayColor = { 0, 255, 0 },
    --     BlipColor = 30,
    -- },
    ["death_sinners"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Death Sinners MC",
        Model = "fw_sprays_death_sinners",
        SprayColor = { 250, 128, 114 },
        BlipColor = 51,
    },
    ["white_widow"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "White Widow",
        Model = "fw_sprays_white_widow",
        SprayColor = { 0, 255, 0 },
        BlipColor = 69,
    },
    -- ["skull_gang"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Skull Gang",
    --     Model = "fw_sprays_skull_gang",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 53,
    -- },
    -- ["grizzley_gang"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Grizzley Gang",
    --     Model = "fw_sprays_grizzley_gang",
    --     SprayColor = { 255, 0, 0 },
    --     BlipColor = 61,
    -- },
    -- ["scum"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Scum",
    --     Model = "fw_sprays_scum",
    --     SprayColor = { 0, 255, 0 },
    --     BlipColor = 56,
    -- },
    ["ballas"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Ballas",
        Model = "fw_sprays_ballas",
        SprayColor = { 128, 0, 128 },
        BlipColor = 7,
    },
    ["wutang"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Wu-Tang",
        Model = "fw_sprays_wutang",
        SprayColor = { 255, 255, 0 },
        BlipColor = 5,
    },
    -- ["nameless"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "The Nameless",
    --     Model = "fw_sprays_nameless",
    --     SprayColor = { 255, 105, 180 },
    --     BlipColor = 8,
    -- },
    -- ["cringeboys"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Cringeboys",
    --     Model = "fw_sprays_cringeboys",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 25,
    -- },
    -- ["21"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "21",
    --     Model = "fw_sprays_21",
    --     SprayColor = { 255, 0, 0 },
    --     BlipColor = 48,
    -- },
    ["vatoslocos"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Vatos Loco's",
        Model = "fw_sprays_vatoslocos",
        SprayColor = { 128, 128, 128 },
        BlipColor = 65,
    },
    ["bumpergang"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "BumperGang",
        Model = "fw_sprays_bumpergang",
        SprayColor = { 255, 0, 0 },
        BlipColor = 1,
    },
    -- ["getbackgang"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Get Back Gang",
    --     Model = "fw_sprays_getbackgang",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 52,
    -- },
    -- ["blackcobras"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Black Cobras",
    --     Model = "fw_sprays_blackcobras",
    --     SprayColor = { 255, 0, 0 },
    --     BlipColor = 50,
    -- },
    -- ["blacklist"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Black Cobras",
    --     Model = "fw_sprays_blacklist",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 31,
    -- },
    -- ["nls"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Black Cobras",
    --     Model = "fw_sprays_nls",
    --     SprayColor = { 255, 255, 255 },
    --     BlipColor = 17,
    -- },
    ["sopranos"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Sopranos",
        Model = "fw_sprays_sopranos",
        SprayColor = { 0, 0, 255 },
        BlipColor = 81,
    },
    ["s2n"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Second2None",
        Model = "fw_sprays_s2n",
        SprayColor = { 255, 255, 255 },
        BlipColor = 23,
    },
    ["fts"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Fock The System",
        Model = "fw_sprays_bakker",
        SprayColor = { 255, 255, 255 },
        BlipColor = 25,
    },
    ["tffc"] = {
        IsGang = true,
        IsBusiness = false,
        Name = "Thieves & Crooks",
        Model = "fw_sprays_tffc",
        SprayColor = { 255, 255, 255 },
        BlipColor = 76,
    },

    -- ["dimeo"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "DiMeo",
    --     Model = "fw_sprays_dimeo",
    --     SprayColor = { 0, 255, 0 },
    --     BlipColor = 81,
    -- },
    -- ["cosanostra"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Cosa Nostra",
    --     Model = "fw_sprays_cosanostra",
    --     SprayColor = { 128, 0, 128 },
    --     BlipColor = 63,
    -- },
    -- ["vdv"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Van Der Veer",
    --     Model = "fw_sprays_vdv",
    --     SprayColor = { 255, 0, 0 },
    --     BlipColor = 28,
    -- },
    -- ["high_table"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "The High Table",
    --     Model = "fw_sprays_high_table",
    --     SprayColor = { 255, 215, 0 },
    --     BlipColor = 46,
    -- },
    -- ["ant"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Ain't No Telling",
    --     Model = "fw_sprays_ant",
    --     SprayColor = { 45, 245, 220 },
    --     BlipColor = 36,
    -- },
    -- ["wanheda"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Wanheda",
    --     Model = "fw_sprays_wanheda",
    --     SprayColor = { 250, 128, 114 },
    --     BlipColor = 51,
    -- },
    -- ["clutch"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Clutch",
    --     Model = "fw_sprays_clutch",
    --     SprayColor = { 0, 255, 0 },
    --     BlipColor = 2,
    -- },
    -- ["bearly_legal_mc"] = {
    --     IsGang = true,
    --     IsBusiness = false,
    --     Name = "Bearly Legal MC",
    --     Model = "fw_sprays_bearlymc",
    --     SprayColor = { 255, 0, 0 },
    --     BlipColor = 76,
    -- },
}