Config = Config or {}

Config.DutyActions = {
    ['Dispatch'] = "Dispatch",
    ['Police'] = "Police",
    ['StoreSecurity'] = "Winkel Cooperatie",
    ['EMS'] = "EMS",
    ['DOC'] = "DOC",
    -- ['lawyer'] = "Advocaat",
    ['judge'] = "Rechter",
}

Config.AlertBlip = {
    ['Agent Gewond'] = 429,
    ['Agent Gewond URGENT'] = 437,
    ['Bolingbroke Penitentiary Alarm'] = 189,
    ['Ambulance Gewond'] = 429,
    ['Ambulance Gewond URGENT'] = 437,
    ['Noodknop'] = 487,
    ['Schoten Gelost uit Voertuig'] = 229,
    ['Schoten Gelost'] = 313,
    ['Gevecht aan de Gang'] = 311,
    ['Dodelijk Gevecht aan de Gang'] = 154,
    ['Gewonde Burger'] = 621,
    ['Juwielier Alarm'] = 617,
    ['Huis Alarm'] = 40,
    ['Banktruck Alarm'] = 477,
    ['Explosie'] = 486,
    ['Gevangenis Alarm'] = 188,
    ['Illegaal Jagen'] = 442,
    ['Anonieme 911 Melding'] = 817,
    ['911 Melding'] = 817,
    ['Ammunation Alarm'] = 110,
    ['Voertuig Diefstal'] = 811,
    ['Bedrijfs Alarm'] = 487,
    ['Fleeca Bank Alarm'] = 354,
    ['Bay City Bank Alarm'] = 354,
    ['Bobcat Security Alarm'] = 354,
    ['Blaine Countys Savings Bank Alarm'] = 354,
    ['City Vault Alarm'] = 618,
    ['Gecontroleerde accountactiviteit'] = 272,
    ['Goederen Tracker Manipulatie'] = 466,
    ['Container Beveiligingssysteem Manipulatie'] = 50,
    ['Persoons overval aan de gang'] = 362,
}