export const Filters = [
    { Timecycle: "Clear", Label: "Filter resetten" },
    { Timecycle: "underwater", Label: "Onderwater" },
    { Timecycle: "WATER_cove", Label: "Onderwater 2" },
    { Timecycle: "underwater_deep", Label: "Diep Onderwater" },
    { Timecycle: "superDARK", Label: "Extra donker" },
    { Timecycle: "CAMERA_BW", Label: "Zwart en wit" },
    { Timecycle: "FRANKLIN", Label: "Gecontrasteerd" },
    { Timecycle: "NEW_abattoir", Label: "Blauwe mist" },
    { Timecycle: "Vagos", Label: "Gele tint" },
    { Timecycle: "cops", Label: "Blauwe tint" },
    { Timecycle: "BikersSPLASH", Label: "Helder blauwe tint" },
    { Timecycle: "VagosSPLASH", Label: "Felgele tint" },
    { Timecycle: "CopsSPLASH", Label: "Felpaarse tint" },
    { Timecycle: "WATER_port", Label: "Groen met vervaging" },
    { Timecycle: "WATER_salton", Label: "Bruin met Blur" },
    { Timecycle: "WATER_muddy", Label: "Close-up vervagen" },
    { Timecycle: "hitped", Label: "Extra bloei" },
    { Timecycle: "dying", Label: "Jaren 80" },
    { Timecycle: "Sniper", Label: "Groene tint" },
    { Timecycle: "blackNwhite", Label: "Alian" },
    { Timecycle: "pulse", Label: "Bloem uit de jaren 80" },
    { Timecycle: "traffic_skycam", Label: "Blauwe tint met ruis" },
    { Timecycle: "telescope", Label: "Telescoop" },
    { Timecycle: "sunglasses", Label: "Zonnebril" },
    { Timecycle: "spectator1", Label: "Retro 1" },
    { Timecycle: "spectator2", Label: "Retro 1 met ruis" },
    { Timecycle: "spectator3", Label: "Retro 2" },
    { Timecycle: "spectator4", Label: "Zwart-wit met ruis" },
    { Timecycle: "spectator5", Label: "Retro dronken" },
    { Timecycle: "spectator6", Label: "Retro 3" },
    { Timecycle: "spectator7", Label: "Retro 4" },
    { Timecycle: "spectator9", Label: "Retro 5" },
    { Timecycle: "spectator10", Label: "Retro 6" },
    { Timecycle: "glasses_blue", Label: "Zonnebril Blauw" },
    { Timecycle: "glasses_red", Label: "Zonnebril Rood" },
    { Timecycle: "glasses_green", Label: "Zonnebril Groen" },
    { Timecycle: "glasses_yellow", Label: "Zonnebril Geel" },
    { Timecycle: "glasses_purple", Label: "Zonnebril Puple" },
    { Timecycle: "glasses_pink", Label: "Zonnebril Roze" },
    { Timecycle: "glasses_orange", Label: "Zonnebril Oranje" },
    { Timecycle: "RemoteSniper", Label: "Noise" },
    { Timecycle: "Bloom", Label: "Bloeien" },
    { Timecycle: "DrivingFocusLight", Label: "Retro groene tint" },
    { Timecycle: "DrivingFocusDark", Label: "Retro donkergroene tint" },
    { Timecycle: "RaceTurboLight", Label: "Donkere turbo" },
    { Timecycle: "RaceTurboDark", Label: "Donkere turbo met bloei" },
    { Timecycle: "BulletTimeDark", Label: "Blauwe tint met bloei" },
    { Timecycle: "REDMIST_blend", Label: "Gebroken sinaasappel" },
    { Timecycle: "MP_Bull_tost_blend", Label: "Groene bloei" },
    { Timecycle: "MP_Powerplay_blend", Label: "Bloemmix" },
    { Timecycle: "MP_Killstreak_blend", Label: "Blauwe mix" },
    { Timecycle: "MP_Loser_blend", Label: "Grijze mix" },
    { Timecycle: "FranklinColorCode", Label: "Groen contrasterend" },
    { Timecycle: "MichaelColorCode", Label: "Blauw contrasterend" },
    { Timecycle: "TrevorColorCode", Label: "Oranje contrasterend" },
    { Timecycle: "PlayerSwitchNeutralFlash", Label: "Wit contrasterend" },
    { Timecycle: "Drunk", Label: "Dronken" },
    { Timecycle: "drug_flying_base", Label: "Retro bloei" },
    { Timecycle: "DRUG_gas_huffin", Label: "Noise #2" },
    { Timecycle: "ExplosionJosh", Label: "Geel helder" },
    { Timecycle: "RaceTurboFlash", Label: "Rood helder" },
    { Timecycle: "MP_job_win", Label: "Oranje Tint" },
    { Timecycle: "NG_filmnoir_BW01", Label: "Noir #1" },
    { Timecycle: "NG_filmnoir_BW02", Label: "Zwart #2" },
    { Timecycle: "NG_filmic10", Label: "Gekke bloei" },
]