Config = Config or {}

Config.Stores = {
    ['247'] = {
        Label = "Shop",
        Items = {
            { Item = "water_bottle", Amount = 20 },
            { Item = "kurkakola", Amount = 20 },
            { Item = "sprunk", Amount = 20 },
            { Item = "sandwich", Amount = 20 },
            { Item = "chocolade", Amount = 20 },
            { Item = "chips", Amount = 20 },
            { Item = "macncheese", Amount = 20 },
            { Item = "bandage", Amount = 20 },
            { Item = "umbrella", Amount = 10 },
            { Item = "bakingsoda", Amount = 20 },
            { Item = "emptybaggies", Amount = 100 },
            { Item = "hairtie", Amount = 10 },
            { Item = "worstenbroodje", Amount = 20 },
            { Item = "notepad", Amount = 1 }
        }
    },
    ['Liqour'] = {
        Label = 'Shop',
        Items = {
            { Item = "water_bottle", Amount = 20 },
            { Item = "kurkakola", Amount = 20 },
            { Item = "sprunk", Amount = 20 },
            { Item = "sandwich", Amount = 20 },
            { Item = "chocolade", Amount = 20 },
            { Item = "bandage", Amount = 20 },
            { Item = "umbrella", Amount = 10 },
            { Item = "bakingsoda", Amount = 20 },
            { Item = "hairtie", Amount = 10 },
        }
    },
    ['Toolshop'] = {
        Label = 'Shop',
        Items = {
            { Item = "armor", Amount = 10 },
            { Item = "dice", Amount = 10 },
            { Item = "coin", Amount = 10 },
            { Item = "scales", Amount = 10 },
            { Item = "fertilizer", Amount = 10 },
            { Item = "trowel", Amount = 1 },
            { Item = "heavy-cutters", Amount = 1 },
            { Item = "binoculars", Amount = 10 },
            { Item = "lawnchair", Amount = 1 },
        }
    },
    ['Drinks & Cocktails'] = {
        Label = 'Shop',
        Items = {
            { Item = "water_bottle", Amount = 20 },
            { Item = "cocktail-split", Amount = 20 },
            { Item = "cocktail-pinacolada", Amount = 20 },
            { Item = "whiskey", Amount = 20 },
            { Item = "sandwich", Amount = 20 },
        }
    },
    ['Locksmith'] = {
        Label = 'Shop',
        Items = {
            { Item = "lockpick", Amount = 20 },
        }
    },
    ['DigitalDen'] = {
        Label = 'Shop',
        Items = {
            { Item = "phone", Amount = 1 },
            -- { Item = "radio", Amount = 1 },
            -- { Item = "printer", Amount = 1 },
            -- { Item = "printer-pack-paper", Amount = 1 },
            -- { Item = "megaphone", Amount = 1 },
        }
    },
    ['Ammunation'] = {
        Label = "Ammunation",
        Items = {
            { Item = "weapon_bat", Amount = 1 },
            { Item = "weapon_crowbar", Amount = 1 },
        }
    },
    ['VendingCandy'] = {
        Label = 'Vending Machine',
        Items = {
            { Item = "420-choco", Amount = 20 },
            { Item = "chips", Amount = 20 },
            { Item = "chocolade", Amount = 20 }
        }
    },
    ['VendingWater'] = {
        Label = 'Water Machine',
        Items = {
            { Item = "water_bottle", Amount = 20 },
        }
    },
    ['VendingSoda'] = {
        Label = 'Soda Machine',
        Items = {
            { Item = "kurkakola", Amount = 20 },
            { Item = "sprunk", Amount = 20 },
            { Item = "fristi", Amount = 20 },
            { Item = "fernandes", Amount = 20 },
        }
    },
    ['VendingCoffee'] = {
        Label = 'Koffie Machine',
        Items = {
            { Item = "coffee", Amount = 20 },
            { Item = "chocomelk", Amount = 20 },
        }
    },
    ['AutoCare'] = {
        Label = 'Hayes AutoCare',
        Items = {
            { Item = "repairkit", Amount = 20 },
            { Item = "tirekit", Amount = 10 },
        }
    },
    ['Mine'] = {
        Label = 'Winkel',
        Items = {
            { Item = "pickaxe", Amount = 1 },
            { Item = "mine-scanner", Amount = 1 }
        }
    },
    ['Hunting'] = {
        Label = 'Sporten & Survival',
        Items = {
            { Item = "weapon_huntingrifle", Amount = 1 },
            { Item = "ammo", Amount = 20, CustomType = "Sniper" },
            { Item = "hunting-knife", Amount = 1 },
            { Item = "hunting-bait", Amount = 20  },
            { Item = "fishingrod", Amount = 1 },
        }
    },
    ['PoliceArmory'] = {
        Label = 'Winkel',
        Items = {
            { Item = "weapon_glock", Amount = 1 },
            { Item = "weapon_fn57", Amount = 1 },
            { Item = "weapon_taser", Amount = 1 },
            { Item = "weapon_m4", Amount = 1 },
            { Item = "weapon_mp7", Amount = 1 },
            { Item = "weapon_flashlight", Amount = 1 },
            { Item = "weapon_nightstick", Amount = 1 },
            { Item = "ammo", Amount = 10, CustomType = "Pistol" },
            { Item = "ammo", Amount = 10, CustomType = "Taser" },
            { Item = "ammo", Amount = 10, CustomType = "Rifle" },
            { Item = "ammo", Amount = 10, CustomType = "Smg" },
            { Item = "heavyarmor", Amount = 5 },
            { Item = "handcuffs", Amount = 5 },
            { Item = "evidence", Amount = 500 },
            { Item = "pdradio", Amount = 1 },
            { Item = "pdcamera", Amount = 1 },
            { Item = "business-bag", Amount = 1, CustomType = "policeduffel" },
            { Item = "scuba-gear", Amount = 1 },
            { Item = "spikestrip", Amount = 1 },
            { Item = "nightvision", Amount = 1 },
            { Item = "ifak", Amount = 20 },
            { Item = "megaphone", Amount = 1 },
            { Item = "detcord", Amount = 10 },
            { Item = "pdwatch", Amount = 1 },
            { Item = "notepad", Amount = 1 },
            { Item = "panicbutton", Amount = 1 }
        }
    },
    ['DocArmory'] = {
        Label = 'Winkel',
        Items = {
            { Item = "weapon_glock", Amount = 1 },
            { Item = "weapon_fn57", Amount = 1 },
            { Item = "weapon_taser", Amount = 1 },
            { Item = "weapon_m4", Amount = 1 },
            { Item = "weapon_mp7", Amount = 1 },
            { Item = "weapon_flashlight", Amount = 1 },
            { Item = "weapon_nightstick", Amount = 1 },
            { Item = "weapon_rubberslug", Amount = 1 },
            { Item = "ammo", Amount = 10, CustomType = "Pistol" },
            { Item = "ammo", Amount = 10, CustomType = "Taser" },
            { Item = "ammo", Amount = 10, CustomType = "Rifle" },
            { Item = "ammo", Amount = 10, CustomType = "Smg" },
            { Item = "ammo", Amount = 10, CustomType = "Rubber" },
            { Item = "heavyarmor", Amount = 5 },
            { Item = "handcuffs", Amount = 5 },
            { Item = "pdradio", Amount = 1 },
            { Item = "pdcamera", Amount = 1 },
            { Item = "ifak", Amount = 20 },
            { Item = "medkit", Amount = 15 },
            { Item = "megaphone", Amount = 1 },
            { Item = "pdwatch", Amount = 1 },
            { Item = "notepad", Amount = 1 },
            { Item = "panicbutton", Amount = 1 }
        }
    },
    ['PoliceHighcommandArmory'] = {
        Label = 'Winkel',
        Items = {
            { Item = "weapon_mpx", Amount = 1 },
            { Item = "weapon_scar", Amount = 1 },
            { Item = "weapon_rubberslug", Amount = 1 },
            { Item = "weapon_remington", Amount = 1 },
            { Item = "weapon_empgun", Amount = 1 },
            { Item = "ammo", Amount = 10, CustomType = "Emp" },
            { Item = "ammo", Amount = 10, CustomType = "Shotgun" },
            { Item = "ammo", Amount = 10, CustomType = "Rubber" },
        }
    },
    ['Hospital'] = {
        Label = 'Winkel',
        Items = {
            { Item = "pdradio", Amount = 1 },
            { Item = "bandage", Amount = 15 },
            { Item = "medkit", Amount = 15 },
            { Item = "weapon_flashlight", Amount = 1 },
            -- { Item = "weapon_fireextinguisher", Amount = 1 },
            { Item = "wheelchair", Amount = 1 },
            { Item = "scootmobile", Amount = 1 },
            { Item = "walkstick", Amount = 1 },
            { Item = "scuba-gear", Amount = 1 },
            { Item = "xray-brain", Amount = 1 },
            { Item = "xray-arm", Amount = 1 },
            { Item = "teddy", Amount = 1 },
            -- { Item = "weapon_crutch", Amount = 1 },
            { Item = "dna-reader", Amount = 1 },
            { Item = "notepad", Amount = 1 },
            { Item = "panicbutton", Amount = 1 }
        },
    },
    ['Medicine'] = {
        Label = 'Medicijnenkastje',
        Items = {
            { Item = "oxy", Amount = 15 },
            { Item = "adrenaline", Amount = 15 },
            { Item = "ibuprofen", Amount = 15 },
            { Item = "ketamine", Amount = 15 },
            { Item = "melatonin", Amount = 15 },
            { Item = "morphine", Amount = 15 },
            { Item = "painkillers", Amount = 15 },
            { Item = "narcose_syringe", Amount = 15 },
        },
    },
    ['Weed'] = {
        Label = "Winkel",
        Items = {
            { Item = "weed-seed-female", Amount = 100 },
            { Item = "rolling-paper", Amount = 100 },
        }
    },
    ['Bees'] = {
        Label = "Bijenwinkel",
        Items = {
            { Item = "beehive", Amount = 20 },
        }
    },
    ['Flightschool'] = {
        Label = "Los Santos Vliegschool",
        Items = {
            { Item = "parachute", Amount = 1 }
        }
    }
}

Config.CraftingBenches = {
    ['General'] = {
        { Item = 'electronickit', Amount = 10, AddRep = 3, RequiredRep = 0 },
        { Item = 'handcuffs', Amount = 10, AddRep = 3, RequiredRep = 60 },
        { Item = 'hacking_device', Amount = 10, AddRep = 2, RequiredRep = 100 },
        { Item = 'ammo', Amount = 10, CustomType = "Pistol", AddRep = 3, RequiredRep = 140 },
        { Item = 'heavy-thermite', Amount = 10, AddRep = 2, RequiredRep = 250 },
        { Item = 'security_hacking_device', Amount = 10, AddRep = 2, RequiredRep = 400 },
    },
    ['Autocare'] = {
        { Item = 'big-repair', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'repairkit', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'car-polish', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'carwax', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'lockpick', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'advlockpick', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
    },
    ['Bennys'] = {
        { Item = 'big-repair', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'repairkit', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'car-polish', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'carwax', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'nitrous', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'harness', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'lockpick', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'advlockpick', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "generic-mechanic-part", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-clutch", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-axle", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-brakes", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-engine", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-injectors", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "S", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "A", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "B", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "C", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "D", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "vehicle-transmission", CustomType = "E", Amount = 20, AddRep = 0, RequiredRep = 0 },
    },
    ['Recycle'] = {
        { Item = "metalscrap", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "steel", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "copper", Amount = 999, AddRep = 0, RequiredRep = 0 },
        -- { Item = "iron", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "aluminum", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "plastic", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "glass", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "rubber", Amount = 999, AddRep = 0, RequiredRep = 0 },
        { Item = "electronics", Amount = 999, AddRep = 0, RequiredRep = 0 },
    },
    ['DigitalDen'] = {
        { Item = "phone", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "radio", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "laptop", Amount = 1, AddRep = 0, RequiredRep = 0 },
        -- { Item = "printer", Amount = 1, AddRep = 0, RequiredRep = 0  },
        { Item = "megaphone", Amount = 20, AddRep = 0, RequiredRep = 0  },
        -- { Item = "printer-pack-paper", Amount = 20, AddRep = 0, RequiredRep = 0  },
    },
    ['DigitalDean'] = {
        { Item = "phone", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "radio", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "laptop", Amount = 1, AddRep = 0, RequiredRep = 0 },
        -- { Item = "printer", Amount = 1, AddRep = 0, RequiredRep = 0  },
        { Item = "megaphone", Amount = 20, AddRep = 0, RequiredRep = 0  },
        { Item = "radioscanner", Amount = 20, AddRep = 0, RequiredRep = 0  },
        -- { Item = "printer-pack-paper", Amount = 20, AddRep = 0, RequiredRep = 0  },
    },
    ['Mattronics'] = {
        { Item = "phone", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "radio", Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = "laptop", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "megaphone", Amount = 20, AddRep = 0, RequiredRep = 0  },
        { Item = "walkman", Amount = 1, AddRep = 0, RequiredRep = 0  },
        { Item = "business-bag", CustomType = "cassettebox", Amount = 1, AddRep = 0, RequiredRep = 0  },
    },
    ['PawnNGo'] = {
        { Item = "polaroid-camera", Amount = 100, AddRep = 0, RequiredRep = 0 },
        { Item = "polaroid-battery", Amount = 100, AddRep = 0, RequiredRep = 0 },
        { Item = "polaroid-paper", Amount = 100, AddRep = 0, RequiredRep = 0 },
        { Item = "polaroid-binder", Amount = 100, AddRep = 0, RequiredRep = 0 },
        { Item = "metaldetector", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "goldpan", CustomType = "small", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "goldpan", CustomType = "medium", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "goldpan", CustomType = "large", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "goldnugget", Amount = 500, AddRep = 0, RequiredRep = 0 },
        { Item = "goldbar", Amount = 500, AddRep = 0, RequiredRep = 0 },
        { Item = "jewelry-part", Amount = 500, AddRep = 0, RequiredRep = 0 },
        -- { Item = "gang-chain", CustomType = "banggang", Amount = 1, AddRep = 0, RequiredRep = 0 },
        -- { Item = "gang-chain", CustomType = "kings", Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['Prison'] = {
        { Item = "weapon_shiv", Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['Scale'] = {
        { Item = 'weed-bag', Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'joint', Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'weed-dried-bud-two', Amount = 100, Multiplier = 2, AddRep = 0, RequiredRep = 0  },
    },
    ['IllegalKnown'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
    },
    ['IllegalWellKnown'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'explosive', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fn502', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fnx', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_beretta', Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['IllegalEstablished'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'explosive', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fn502', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fnx', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_beretta', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_heavypistol', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_colt', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_glock18c', Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['IllegalRespected'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'explosive', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fn502', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fnx', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_heavypistol', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_beretta', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_colt', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_glock18c', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_draco', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_uzi', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_mac10', Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['IllegalFeared'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'explosive', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fn502', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fnx', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_heavypistol', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_beretta', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_colt', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_glock18c', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_draco', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_uzi', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_mac10', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_mp5', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_ak74', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_m70', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_groza', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_expedite', Amount = 1, AddRep = 0, RequiredRep = 0 },
    },
    ['IllegalPowerful'] = {
        { Item = 'ammo', Amount = 10, CustomType = "Rifle", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Smg", AddRep = 0, RequiredRep = 0 },
        { Item = 'ammo', Amount = 10, CustomType = "Shotgun", AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer_oilcan', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'silencer', Amount = 20, AddRep = 0, RequiredRep = 0 },
        { Item = 'explosive', Amount = 10, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fn502', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_fnx', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_heavypistol', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_beretta', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_colt', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_glock18c', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_draco', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_uzi', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_mac10', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_mp5', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_ak74', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_m70', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_groza', Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = 'weapon_expedite', Amount = 1, AddRep = 0, RequiredRep = 0 },
        -- { Item = 'weapon_grenade', Amount = 1, AddRep = 0, RequiredRep = 0 },
    },

    -- 2.1
    ['CocaineBrick'] = {
        { Item = "10gcocaine", Amount = 1, Multiplier = 100, AddRep = 0, RequiredRep = 0 },
    },
    ['BakingSoda'] = {
        { Item = "5gcrack", Amount = 80, AddRep = 0, RequiredRep = 0 },
    },
    ['GlassPipes'] = {
        { Item = "crackpipe", Amount = 1, AddRep = 0, RequiredRep = 0 },
        { Item = "methpipe", Amount = 1, AddRep = 0, RequiredRep = 0 },
    },

    ['WhiteWidow'] = {
        { Item = 'weed-bag-1g', Amount = 100, Multiplier = 7, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "1g", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "spacecake", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "hashbrownies", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "insideout", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "cone", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "splitter", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "cross", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "tulp", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'customjoint', CustomType = "windmill", Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'bong', Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'fertilizer', Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'scales', Amount = 100, AddRep = 0, RequiredRep = 0  },
        { Item = 'emptybaggies', Amount = 100, AddRep = 0, RequiredRep = 0  },
    },
}