Config = Config or {}

Config.PropList = {
    -- Casual Props
    ['Megaphone'] = {   
		["name"] = "Megaphone",
        ['prop'] = 'prop_megaphone_01',
        ['hash'] = GetHashKey('prop_megaphone_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ["X"] = 0.04,
            ["Y"] = -0.01,
            ["Z"] = 0.0,
            ["XR"] = 22.0,
            ["YR"] = -4.0,
            ["ZR"] = 87.0,
        },
	},
    ['PBadge'] = {
        ['name'] = 'Politie Badge',
        ['prop'] = 'fw_policebadge_01',
        ['hash'] = GetHashKey('fw_policebadge_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = -0.06,
            ['XR'] = 40.0,
            ['YR'] = 55.0,
            ['ZR'] = -267.0
        },
    },
    ['Drill'] = {
        ['name'] = 'Drill Boor',
        ['prop'] = 'hei_prop_heist_drill',
        ['hash'] = GetHashKey('hei_prop_heist_drill'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.14,
            ['Y'] = 0.0,
            ['Z'] = -0.01,
            ['XR'] = 90.0,
            ['YR'] = -90.0,
            ['ZR'] = 180.0,
        },
    },
    ['Duffel'] = {
        ['name'] = 'DuffelBag',
        ['prop'] = 'xm_prop_x17_bag_01a',
        ['hash'] = GetHashKey('xm_prop_x17_bag_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.27,
            ['Y'] = 0.15,
            ['Z'] = 0.05,
            ['XR'] = 35.0,
            ['YR'] = -125.0,
            ['ZR'] = 50.0,
        },
    },
    ['Trash'] = {
        ['name'] = 'Trash',
        ['prop'] = 'prop_cs_rub_binbag_01',
        ['hash'] = GetHashKey('prop_cs_rub_binbag_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.12,
            ['Y'] = 0.0,
            ['Z'] = -0.05,
            ['XR'] = 220.0,
            ['YR'] = 120.0,
            ['ZR'] = 0.0,
        },
    },
    ['Cup'] = {
        ['name'] = 'Papieren Beker',
        ['prop'] = 'prop_cs_paper_cup',
        ['hash'] = GetHashKey('prop_cs_paper_cup'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['FishingRod'] = {
        ['name'] = 'Vis Hengel',
        ['prop'] = 'prop_fishing_rod_01',
        ['hash'] = GetHashKey('prop_fishing_rod_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.08,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = -100.0,
            ['YR'] = 0.0,
            ['ZR'] = -20.0,
        },
    },
    ['Boombox'] = {
        ['name'] = 'Boombox',
        ['prop'] = 'prop_boombox_01',
        ['hash'] = GetHashKey('prop_boombox_01'),
        ['bone-index'] = {
            ['bone'] = 1,
            ['X'] = 1,
            ['Y'] = 1,
            ['Z'] = 1,
            ['XR'] = 1,
            ['YR'] = 1,
            ['ZR'] = 1,
        },
    },
    ['Pills'] = {
        ['name'] = 'Pillen',
        ['prop'] = 'prop_cs_pills',
        ['hash'] = GetHashKey('prop_cs_pills'),
        ['bone-index'] = {
            ['bone'] = 1,
            ['X'] = 1,
            ['Y'] = 1,
            ['Z'] = 1,
            ['XR'] = 1,
            ['YR'] = 1,
            ['ZR'] = 1,
        },
    },
    ['ShoppingBag'] = {
        ['name'] = 'Shop Tassen',
        ['prop'] = 'prop_shopping_bags01',
        ['hash'] = GetHashKey('prop_shopping_bags01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.05,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 35.0,
            ['YR'] = -125.0,
            ['ZR'] = 0.0,
        },
    },
    ['CrackPipe'] = {
        ['name'] = 'Crack Pijp',
        ['prop'] = 'prop_cs_crackpipe',
        ['hash'] = GetHashKey('prop_cs_crackpipe'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = 135.0,
            ['YR'] = -100.0,
            ['ZR'] = 0.0,
        },
    },
    ['Bong'] = {
        ['name'] = 'Bongetje',
        ['prop'] = 'prop_bong_01',
        ['hash'] = GetHashKey('prop_bong_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.11,
            ['Y'] = -0.23,
            ['Z'] = 0.01,
            ['XR'] = -90.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['HealthPack'] = {
        ['name'] = 'EHBO Kit',
        ['prop'] = 'prop_ld_health_pack',
        ['hash'] = GetHashKey('prop_ld_health_pack'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.15,
            ['Y'] = 0.08,
            ['Z'] = 0.1,
            ['XR'] = 180.0,
            ['YR'] = 220.0,
            ['ZR'] = 0.0,
        },
    },
    ['ReporterCam'] = {
        ['name'] = 'Weazel News Camera',
        ['prop'] = 'prop_v_cam_01',
        ['hash'] = GetHashKey('prop_v_cam_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.13,
            ['Y'] = 0.25,
            ['Z'] = -0.03,
            ['XR'] = -85.0,
            ['YR'] = 0.0,
            ['ZR'] = -80.0,
        },
    },
    ['ReporterMic'] = {
        ['name'] = 'Weazel News Mic',
        ['prop'] = 'p_ing_microphonel_01',
        ['hash'] = GetHashKey('p_ing_microphonel_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.1,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = -85.0,
            ['YR'] = -80.0,
            ['ZR'] = -80.0,
        },
    },
    ['BriefCase'] = {
        ['name'] = 'Koffer',
        ['prop'] = 'prop_security_case_01',
        ['hash'] = GetHashKey('prop_security_case_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.1,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 280.0,
            ['ZR'] = 53.0,
        },
    },
    ['GunCase'] = {
        ['name'] = 'Een wapen koffer',
        ['prop'] = 'prop_box_guncase_01a',
        ['hash'] = GetHashKey('prop_box_guncase_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.18,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = 215.0,
            ['YR'] = -175.0,
            ['ZR'] = 100.0,
        },
    },
    ['Pickaxe'] = {
        ['name'] = 'Een pikhouweel',
        ['prop'] = 'prop_tool_pickaxe',
        ['hash'] = GetHashKey('prop_tool_pickaxe'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.09,
            ['Y'] = 0.03,
            ['Z'] = -0.02,
            ['XR'] = -78.0,
            ['YR'] = 13.0,
            ['ZR'] = 345.0,
        },
    },
    ['DarkmarketBox'] = {
        ['name'] = 'Een doos',
        ['prop'] = 'prop_idol_case_01',
        ['hash'] = GetHashKey('prop_idol_case_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.02,
            ['Z'] = -0.22,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['Phone'] = {
        ['name'] = 'Een telefoon',
        ['prop'] = 'prop_npc_phone_02',
        ['hash'] = GetHashKey('prop_npc_phone_02'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['Tablet'] = {
        ['name'] = 'Een politie tablet',
        ['prop'] = 'prop_cs_tablet',
        ['hash'] = GetHashKey('prop_cs_tablet'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = 0.03,
            ['Y'] = 0.002,
            ['Z'] = -0.0,
            ['XR'] = 0.0,
            ['YR'] = 160.0,
            ['ZR'] = 0.0,
        },
    },
    ['Box'] = {
        ['name'] = 'Een doos',
        ['prop'] = 'prop_cs_cardbox_01',
        ['hash'] = GetHashKey('prop_cs_cardbox_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.05,
            ['Y'] = 0.1,
            ['Z'] = -0.3,
            ['XR'] = 300.0,
            ['YR'] = 250.0,
            ['ZR'] = 20.0,
        },
    },
    ['Vase'] = {
        ['name'] = 'Een vaas',
        ['prop'] = 'v_med_p_vaseround',
        ['hash'] = GetHashKey('v_med_p_vaseround'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.22,
            ['Y'] = -0.12,
            ['Z'] = -0.46,
            ['XR'] = -23.99,
            ['YR'] = -32.77,
            ['ZR'] = 2.87
        },
    },
    ['Painting'] = {
        ['name'] = 'Een vaas',
        ['prop'] = 'h4_prop_h4_painting_01c',
        ['hash'] = GetHashKey('h4_prop_h4_painting_01c'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.24,
            ['Y'] = -0.05,
            ['Z'] = -0.17,
            ['XR'] = -143.88,
            ['YR'] = 65.78,
            ['ZR'] = -12.50
        },
    },
    ['HeistBag'] = {
        ['name'] = 'Een tas',
        ['prop'] = 'prop_cs_heist_bag_02',
        ['hash'] = GetHashKey('prop_cs_heist_bag_02'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = -0.005,
            ['Y'] = 0.0,
            ['Z'] = -0.16,
            ['XR'] = 250.0,
            ['YR'] = -30.0,
            ['ZR'] = 0.0,
        },
    },
    ['StolenTv'] = {
        ['name'] = 'Een tv',
        ['prop'] = 'prop_tv_flat_02',
        ['hash'] = GetHashKey('prop_tv_flat_02'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    ['StolenPc'] = {
        ['name'] = 'Een computer',
        ['prop'] = 'prop_dyn_pc_02',
        ['hash'] = GetHashKey('prop_dyn_pc_02'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.22,
            ['XR'] = -80.00,
            ['YR'] = -15.00,
            ['ZR'] = -60.00,
        },
    },
    ['StolenMicro'] = {
        ['name'] = 'Een magnetron',
        ['prop'] = 'prop_microwave_1',
        ['hash'] = GetHashKey('prop_microwave_1'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.30,
            ['Y'] = 0.15,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    ['Notepad'] = {
        ['name'] = 'Notepad',
        ['prop'] = 'prop_notepad_01',
        ['hash'] = GetHashKey('prop_notepad_01'),
        ['bone-index'] = {
            ["bone"] = 60309,
            ["X"] = 0.0,
            ["Y"] = -0.0,
            ["Z"] = -0.0,
            ["XR"] = 0.0,
            ["YR"] = 0.0,
            ["ZR"] = 0.0
        },
    },
    ['Pencil'] = {
        ['name'] = 'Notepad',
        ['prop'] = 'prop_pencil_01',
        ['hash'] = GetHashKey('prop_pencil_01'),
        ['bone-index'] = {
            ["bone"] = 58870,
            ["X"] = 0.04,
            ["Y"] = 0.0225,
            ["Z"] = 0.08,
            ["XR"] = 320.0,
            ["YR"] = 0.0,
            ["ZR"] = 220.0
        },
    },
    ['Clipboard'] = {
        ['name'] = 'Clipboard',
        ['prop'] = 'p_amb_clipboard_01',
        ['hash'] = GetHashKey('p_amb_clipboard_01'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = -0.01,
            ['Y'] = -0.015,
            ['Z'] = 0.005,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = -10.0,
        },
    },
    ['TennisRack'] = {
        ['name'] = 'Tennis',
        ['prop'] = 'prop_tennis_rack_01',
        ['hash'] = GetHashKey('prop_tennis_rack_01'),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = 0.0,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 0.0,
            ["YR"] = 0.0,
            ["ZR"] = 0.0
        },
    },
    ['ToyHorse'] = {
        ['name'] = 'ToyHorse',
        ['prop'] = 'ba_prop_battle_hobby_horse',
        ['hash'] = GetHashKey('ba_prop_battle_hobby_horse'),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = 0.0,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 0.0,
            ["YR"] = 0.0,
            ["ZR"] = 0.0
        },
    },
    ['Cigarette'] = {
        ['name'] = 'Cigarette',
        ['prop'] = 'prop_cs_ciggy_01',
        ['hash'] = GetHashKey('prop_cs_ciggy_01'),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = -0.0,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 0.0,
            ["YR"] = 0.0,
            ["ZR"] = 0.0
        },
    },
    ['CigMouth'] = {
        ['name'] = 'Cigarette',
        ['prop'] = 'prop_amb_ciggy_01',
        ['hash'] = GetHashKey('prop_amb_ciggy_01'),
        ['bone-index'] = {
            ["bone"] = 47419,
            ["X"] = 0.010,
            ["Y"] = -0.009,
            ["Z"] = -0.003,
            ["XR"] = 55.0,
            ["YR"] = 0.0,
            ["ZR"] = 110.0
        },
    },
    ['Cigar'] = {
        ['name'] = 'Cigar',
        ['prop'] = "prop_cigar_01",
        ['hash'] = GetHashKey("prop_cigar_01"),
        ['bone-index'] = {
            ["bone"] = 47419,
            ["X"] = 0.010,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 50.0,
            ["YR"] = 0.0,
            ["ZR"] = -80.0
        },
    },
    ['Cigar2'] = {
        ['name'] = 'Cigar',
        ['prop'] = "prop_cigar_02",
        ['hash'] = GetHashKey("prop_cigar_02"),
        ['bone-index'] = {
            ["bone"] = 47419,
            ["X"] = 0.010,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 50.0,
            ["YR"] = 0.0,
            ["ZR"] = -80.0
        },
    },
    ['Cigar3'] = {
        ['name'] = 'Cigar',
        ['prop'] = "prop_cigar_03",
        ['hash'] = GetHashKey("prop_cigar_03"),
        ['bone-index'] = {
            ["bone"] = 47419,
            ["X"] = 0.010,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 50.0,
            ["YR"] = 0.0,
            ["ZR"] = -80.0
        },
    },
    ['Broom'] = {
        ['name'] = 'Broom',
        ['prop'] = "prop_tool_broom",
        ['hash'] = GetHashKey("prop_tool_broom"),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = 0.0,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 0.0,
            ["YR"] = 0.0,
            ["ZR"] = 0.0,
        },
    },
    ['Umbrella'] = {
        ['name'] = 'Broom',
        ['prop'] = "p_amb_brolly_01",
        ['hash'] = GetHashKey("p_amb_brolly_01"),
        ['bone-index'] = {
            ["bone"] = 57005,
            ["X"] = 0.15,
            ["Y"] = 0.005,
            ["Z"] = 0.0,
            ["XR"] = 87.0,
            ["YR"] = -20.0,
            ["ZR"] = 180.0,
        },
    },
    ['GlowstickLeft'] = {
        ['name'] = 'GlowstickLeft',
        ['prop'] = "ba_prop_battle_glowstick_01",
        ['hash'] = GetHashKey("ba_prop_battle_glowstick_01"),
        ['bone-index'] = {
            ["bone"] = 60309,
            ["X"] = 0.0700,
            ["Y"] = 0.0900,
            ["Z"] = 0.0,
            ["XR"] = -120.0,
            ["YR"] = 20.0,
            ["ZR"] = 0.0
        },
    },
    ['GlowstickRight'] = {
        ['name'] = 'GlowstickRight',
        ['prop'] = "ba_prop_battle_glowstick_01",
        ['hash'] = GetHashKey("ba_prop_battle_glowstick_01"),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = 0.0700,
            ["Y"] = 0.1400,
            ["Z"] = 0.0,
            ["XR"] = -80.0,
            ["YR"] = 20.0,
            ["ZR"] = 0.0
        },
    },
    ['Teddy'] = {
        ['name'] = 'Teddy',
        ['prop'] = "v_ilev_mr_rasberryclean",
        ['hash'] = GetHashKey("v_ilev_mr_rasberryclean"),
        ['bone-index'] = {
            ["bone"] = 24817,
            ["X"] = -0.20,
            ["Y"] = 0.46,
            ["Z"] = -0.016,
            ["XR"] = -180.0,
            ["YR"] = -90.0,
            ["ZR"] = 0.0
        },
    },
    ['WadeOfBills'] = {
        ['name'] = 'Bills',
        ['prop'] = "prop_anim_cash_pile_01",
        ['hash'] = GetHashKey("prop_anim_cash_pile_01"),
        ['bone-index'] = {
            ["bone"] = 60309,
            ["X"] = 0.0,
            ["Y"] = 0.0,
            ["Z"] = 0.0,
            ["XR"] = 180.0,
            ["YR"] = 0.0,
            ["ZR"] = 70.0
        },
    },
    ['FirstAid'] = {
        ['name'] = 'FirstAid',
        ['prop'] = "v_ret_ta_firstaid",
        ['hash'] = GetHashKey("v_ret_ta_firstaid"),
        ['bone-index'] = {
            ["bone"] = 60309,
            ["X"] = 0.16,
            ["Y"] = 0.01,
            ["Z"] = 0.04,
            ["XR"] = -41.19,
            ["YR"] = -65.27,
            ["ZR"] = 106.31,
        },
    },
    ['SyringeNeck'] = {
        ['name'] = 'Syringe Neck',
        ['prop'] = "prop_syringe_01",
        ['hash'] = GetHashKey("prop_syringe_01"),
        ['bone-index'] = {
            ["bone"] = 39317,
            ["X"] = 0.05,
            ["Y"] = -0.01,
            ["Z"] = 0.14,
            ["XR"] = 21.39,
            ["YR"] = 0.89,
            ["ZR"] = -18.46,
        },
    },
    ['SyringeThigh'] = {
        ['name'] = 'Syringe Thigh',
        ['prop'] = "prop_syringe_01",
        ['hash'] = GetHashKey("prop_syringe_01"),
        ['bone-index'] = {
            ["bone"] = 58271,
            ["X"] = 0.14,
            ["Y"] = 0.19,
            ["Z"] = -0.08,
            ["XR"] = -124.22,
            ["YR"] = 0.00,
            ["ZR"] = 0.00,
        },
    },
    ['SyringeArm'] = {
        ['name'] = 'Syringe Arm',
        ['prop'] = "prop_syringe_01",
        ['hash'] = GetHashKey("prop_syringe_01"),
        ['bone-index'] = {
            ["bone"] = 45509,
            ["X"] = 0.04,
            ["Y"] = -0.05,
            ["Z"] = -0.11,
            ["XR"] = 162.50,
            ["YR"] = 28.18,
            ["ZR"] = 23.42,
        },
    },
    ['BeanBag'] = {
        ['name'] = 'Bean Bag',
        ['prop'] = "v_corp_facebeanbag",
        ['hash'] = GetHashKey("v_corp_facebeanbag"),
        ['bone-index'] = {
            ["bone"] = 0,
            ["X"] = -0.00,
            ["Y"] = -0.23,
            ["Z"] = -0.06,
            ["XR"] = 59.75,
            ["YR"] = -1.58,
            ["ZR"] = -179.07,
        },
    },
    ['Cushion'] = {
        ['name'] = 'Cushion',
        ['prop'] = "v_res_tre_cushiona",
        ['hash'] = GetHashKey("v_res_tre_cushiona"),
        ['bone-index'] = {
            ["bone"] = 0,
            ["X"] = -0.00,
            ["Y"] = -0.10,
            ["Z"] = -0.12,
            ["XR"] = -44.54,
            ["YR"] = 0,
            ["ZR"] = 0
        },
    },
    ['Plunger'] = {
        ['name'] = 'Plunger',
        ['prop'] = "v_res_tt_plunger",
        ['hash'] = GetHashKey("v_res_tt_plunger"),
        ['bone-index'] = {
            ["bone"] = 31086,
            ["X"] = 0.20,
            ["Y"] = 0.01,
            ["Z"] = 0.00,
            ["XR"] = 4.00,
            ["YR"] = 88.50,
            ["ZR"] = -114.20,
        },
    },
    ['Bag'] = {
        ['name'] = 'Bag',
        ['prop'] = "v_ret_gc_bag02",
        ['hash'] = GetHashKey("v_ret_gc_bag02"),
        ['bone-index'] = {
            ["bone"] = 28422,
            ["X"] = 0.23,
            ["Y"] = -0.12,
            ["Z"] = -0.06,
            ["XR"] = -22.24,
            ["YR"] = -69.24,
            ["ZR"] = 32.61,
        },
    },
    ['Knife'] = {
        ['name'] = 'Knife',
        ['prop'] = "w_me_knife_xm3_06",
        ['hash'] = GetHashKey("w_me_knife_xm3_06"),
        ['bone-index'] = {
            ["bone"] = 11816,
            ["X"] = -0.3,
            ["Y"] = 0.35,
            ["Z"] = -0.05,
            ["XR"] = 79.02,
            ["YR"] = 90.14,
            ["ZR"] = -11.62,
        },
    },
    -- Food Props
    ['hamburger'] = {
        ['name'] = 'Broodje Hamburger',
        ['prop'] = 'prop_cs_burger_01',
        ['hash'] = GetHashKey('prop_cs_burger_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 120.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['sandwich'] = {
        ['name'] = 'Sandwich',
        ['prop'] = 'prop_sandwich_01',
        ['hash'] = GetHashKey('prop_sandwich_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['chocolade'] = {
        ['name'] = 'Chocolade',
        ['prop'] = 'prop_choc_meto',
        ['hash'] = GetHashKey('prop_choc_meto'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['donut'] = {
        ['name'] = 'Donut',
        ['prop'] = 'prop_amb_donut',
        ['hash'] = GetHashKey('prop_amb_donut'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['taco'] = {
        ['name'] = 'Tacootje',
        ['prop'] = 'prop_taco_01',
        ['hash'] = GetHashKey('prop_taco_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 160.0,
            ['YR'] = 0.0,
            ['ZR'] = -50.0,
        },
    },
    ['chips'] = {
        ['name'] = 'Chips',
        ['prop'] = 'ng_proc_food_chips01b',
        ['hash'] = GetHashKey('ng_proc_food_chips01b'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.20,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 220.0,
            ['YR'] = 0.0,
            ['ZR'] = -160.0,
        },
    },
    ['macncheese'] = {
        ['name'] = 'Macncheese',
        ['prop'] = 'v_res_fa_potnoodle',
        ['hash'] = GetHashKey('v_res_fa_potnoodle'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 160.0,
            ['YR'] = 0.0,
            ['ZR'] = -160.0,
        },
    },
    ['burger-fries'] = {
        ['name'] = 'Frietekes',
        ['prop'] = 'prop_food_bs_chips',
        ['hash'] = GetHashKey('prop_food_bs_chips'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.12,
            ['Y'] = 0.04,
            ['Z'] = 0.05,
            ['XR'] = 130.0,
            ['YR'] = 8.0,
            ['ZR'] = 200.0,
        },
    },
    ['apple'] = {
        ['name'] = 'Apple',
        ['prop'] = 'ng_proc_food_aple2a',
        ['hash'] = GetHashKey('ng_proc_food_aple2a'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.15,
            ['Y'] = 0.09,
            ['Z'] = 0.09,
            ['XR'] = 180.0,
            ['YR'] = 0.0,
            ['ZR'] = -50.0,
        },
    },
    ['banana'] = {
        ['name'] = 'Banana',
        ['prop'] = 'ng_proc_food_nana1a',
        ['hash'] = GetHashKey('ng_proc_food_nana1a'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.16,
            ['Y'] = 0.02,
            ['Z'] = 0.04,
            ['XR'] = 160.0,
            ['YR'] = 0.0,
            ['ZR'] = -50.0,
        },
    },
    -- Drink Props
    ['water'] = {
        ['name'] = 'Flesje Water',
        ['prop'] = 'prop_ld_flow_bottle',
        ['hash'] = GetHashKey('prop_ld_flow_bottle'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['cocktail'] = {
        ['name'] = 'Cocktailtje',
        ['prop'] = 'prop_cocktail',
        ['hash'] = GetHashKey('prop_cocktail'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.1,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['beer'] = {
        ['name'] = 'Beer',
        ['prop'] = 'prop_cs_beer_bot_01',
        ['hash'] = GetHashKey('prop_cs_beer_bot_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.1,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['coffee'] = {
        ['name'] = 'KOFFIEEE',
        ['prop'] = 'p_amb_coffeecup_01',
        ['hash'] = GetHashKey('p_amb_coffeecup_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['tea'] = {
        ['name'] = 'Thee',
        ['prop'] = 'prop_mug_02',
        ['hash'] = GetHashKey('prop_mug_02'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['cola'] = {
        ['name'] = 'Lekker blikkie cola',
        ['prop'] = 'prop_ecola_can',
        ['hash'] = GetHashKey('prop_ecola_can'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['burger-soft'] = {
        ['name'] = 'Soft Drink',
        ['prop'] = 'ng_proc_sodacup_01a',
        ['hash'] = GetHashKey('ng_proc_sodacup_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.07,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['wateringcan'] = {
        ['name'] = 'Gieter',
        ['prop'] = 'prop_wateringcan',
        ['hash'] = GetHashKey('prop_wateringcan'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.32,
            ['Y'] = -0.07,
            ['Z'] = -0.1,
            ['XR'] = 211.5,
            ['YR'] = 65.5,
            ['ZR'] = 2.57
        },
    },
    ['fuelnuzzle'] = {
        ['name'] = 'Tankpistool',
        ['prop'] = 'prop_cs_fuel_nozle',
        ['hash'] = GetHashKey('prop_cs_fuel_nozle'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.11,
            ['Y'] = 0.0,
            ['Z'] = 0.03,
            ['XR'] = -262.15,
            ['YR'] = 53.43,
            ['ZR'] = 162.29
        },
    },
    ['goldpan'] = {
        ['name'] = 'Gold Panning Tray',
        ['prop'] = 'v_res_r_silvrtray',
        ['hash'] = GetHashKey('v_res_r_silvrtray'),
        ['bone-index'] = {
            ['bone'] = 14201,
            ['X'] = 0.6,
            ['Y'] = 0.1,
            ['Z'] = 0.2,
            ['XR'] = 60.0,
            ['YR'] = 90.0,
            ['ZR'] = 180.0
        },
    },
    ['lawnchair'] = {
        ['name'] = 'Lawnchair',
        ['prop'] = 'prop_skid_chair_02',
        ['hash'] = GetHashKey('prop_skid_chair_02'),
        ['bone-index'] = {
            ['bone'] = 0,
            ['X'] = 0.0,
            ['Y'] = -0.12,
            ['Z'] = -0.16,
            ['XR'] = 5.0,
            ['YR'] = -1.0,
            ['ZR'] = -187.0
        },
    },

    -- 2.1
    ['Pizza'] = {
        ['name'] = 'Pizza',
        ['prop'] = 'robijn_props_pizza',
        ['hash'] = GetHashKey('robijn_props_pizza'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.04,
            ['Z'] = 0.01,
            ['XR'] = 244.8,
            ['YR'] = 28.35,
            ['ZR'] = -96.05,
        },
    },
    ['ATM'] = {
        ['name'] = 'ATM',
        ['prop'] = 'fw_atm_02_console',
        ['hash'] = GetHashKey('fw_atm_02_console'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.02,
            ['Z'] = -0.84,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['PolaroidPhotobook'] = {
        ['name'] = 'Polaroid Photobook',
        ['prop'] = 'fw_polaroid_binder',
        ['hash'] = GetHashKey('fw_polaroid_binder'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = 0.1,
            ['Y'] = 0.0,
            ['Z'] = -0.15,
            ['XR'] = 90.0,
            ['YR'] = 100.0,
            ['ZR'] = 0.0,
        },
    },
    ['PolaroidPhoto'] = {
        ['name'] = 'Polaroid Photo',
        ['prop'] = 'fw_polaroid_card',
        ['hash'] = GetHashKey('fw_polaroid_card'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.055,
            ['Z'] = -0.025,
            ['XR'] = 100.0,
            ['YR'] = 53.0,
            ['ZR'] = -240.0,
        },
    },
    ['PolaroidCamera1'] = {
        ['name'] = 'Polaroid Camera',
        ['prop'] = 'fw_polaroid1',
        ['hash'] = GetHashKey('fw_polaroid1'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.18,
            ['Y'] = 0.02,
            ['Z'] = -0.09,
            ['XR'] = 16.0,
            ['YR'] = 53.0,
            ['ZR'] = 7.0,
        },
    },
    ['PolaroidCamera2'] = {
        ['name'] = 'Polaroid Camera',
        ['prop'] = 'fw_polaroid2',
        ['hash'] = GetHashKey('fw_polaroid2'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.18,
            ['Y'] = 0.02,
            ['Z'] = -0.09,
            ['XR'] = 16.0,
            ['YR'] = 53.0,
            ['ZR'] = 7.0,
        },
    },
    ['PolaroidCamera3'] = {
        ['name'] = 'Polaroid Camera',
        ['prop'] = 'fw_polaroid3',
        ['hash'] = GetHashKey('fw_polaroid3'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.18,
            ['Y'] = 0.02,
            ['Z'] = -0.09,
            ['XR'] = 16.0,
            ['YR'] = 53.0,
            ['ZR'] = 7.0,
        },
    },
    ['Book'] = {
        ['name'] = 'Open Boek',
        ['prop'] = 'v_ilev_mp_bedsidebook',
        ['hash'] = GetHashKey('v_ilev_mp_bedsidebook'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = 0.05,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = -90.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0
        },
    },
    ['PaparazziCamera'] = {
        ['name'] = 'Paparazzi Camera',
        ['prop'] = 'prop_pap_camera_01',
        ['hash'] = GetHashKey('prop_pap_camera_01'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = -0.031777119577214,
            ['Y'] = -0.12510567524511,
            ['Z'] = 0.10330419649438,
            ['XR'] = 16.195737363116,
            ['YR'] = -2.4208881076528,
            ['ZR'] = 120.40556169923,
        },
    },
}