Config = Config or {}
Config.WeaponData = false

Config.TypeToAmmo = {
    ["Pistol"] = "AMMO_PISTOL",
    ["Rifle"] = "AMMO_RIFLE",
    ["Smg"] = "AMMO_SMG",
    ["Shotgun"] = "AMMO_SHOTGUN",
    ["Taser"] = "AMMO_TASER",
    ["Paintball"] = "AMMO_PAINTBALL",
    ["Sniper"] = "AMMO_SNIPER",
    ["Emp"] = "AMMO_EMP",
    ["Rubber"] = "AMMO_RUBBER_SHOTGUN",
    ["Revolver"] = "AMMO_REVOLVER",
    ["Snowball"] = "AMMO_SNOWBALLLAUNCHER",
}

Config.DurabilityBlockedWeapons = {"weapon_unarmed", "weapon_molotov", "weapon_brick", "weapon_flare", "weapon_smokegrenade", "weapon_shoe", "weapon_fireextinguisher"}

Config.Weapons = {
    [GetHashKey('weapon_taser')] = {
        WeaponID = 'weapon_taser',  
        AmmoType = 'AMMO_TASER',
        SelectFire = false,
        MaxAmmo = 3,
        AddAmmo = 1,
    },
    [GetHashKey('weapon_paintball')] = {
        WeaponID = 'weapon_paintball',  
        AmmoType = 'AMMO_PAINTBALL',
        SelectFire = false,
        MaxAmmo = 200,
        AddAmmo = 100,
    },
    [GetHashKey('weapon_beretta')] = {
        WeaponID = 'weapon_beretta',  
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_colt')] = {
        WeaponID = 'weapon_colt',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_glock')] = {
        WeaponID = 'weapon_glock',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_fnx')] = {
        WeaponID = 'weapon_fnx',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_fn57')] = {
        WeaponID = 'weapon_fn57',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_fn502')] = {
        WeaponID = 'weapon_fn502',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_glock18c')] = {
        WeaponID = 'weapon_glock18c',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_python')] = {
        WeaponID = 'weapon_python',   
        AmmoType = 'AMMO_REVOLVER',
        SelectFire = false,
        MaxAmmo = 24,
        AddAmmo = 12,
    },
    [GetHashKey('weapon_diamond')] = {
        WeaponID = 'weapon_diamond',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_heavypistol')] = {
        WeaponID = 'weapon_heavypistol',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = false,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_appistol')] = {
        WeaponID = 'weapon_appistol',   
        AmmoType = 'AMMO_PISTOL',
        SelectFire = true,
        MaxAmmo = 100,
        AddAmmo = 50,
    },
    [GetHashKey('weapon_mac10')] = {
        WeaponID = 'weapon_mac10',  
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_uzi')] = {
        WeaponID = 'weapon_uzi',    
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_draco')] = {
        WeaponID = 'weapon_draco',    
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_mp5')] = {
        WeaponID = 'weapon_mp5',    
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_mp7')] = {
        WeaponID = 'weapon_mp7',    
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_mpx')] = {
        WeaponID = 'weapon_mpx',    
        AmmoType = 'AMMO_SMG',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_m4')] = {
        WeaponID = 'weapon_m4',     
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_scar')] = {
        WeaponID = 'weapon_scar',     
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_groza')] = {
        WeaponID = 'weapon_groza',    
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_m70')] = {
        WeaponID = 'weapon_m70',    
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_ak47')] = {
        WeaponID = 'weapon_ak47',   
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_ak74')] = {
        WeaponID = 'weapon_ak74',   
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 240,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_rpk')] = {
        WeaponID = 'weapon_rpk',   
        AmmoType = 'AMMO_RIFLE',
        SelectFire = true,
        MaxAmmo = 300,
        AddAmmo = 60,
    },
    [GetHashKey('weapon_remington')] = {
        WeaponID = 'weapon_remington',   
        AmmoType = 'AMMO_SHOTGUN',
        SelectFire = false,
        MaxAmmo = 60,
        AddAmmo = 12,
    },
    [GetHashKey('weapon_expedite')] = {
        WeaponID = 'weapon_expedite',
        AmmoType = 'AMMO_SHOTGUN',
        SelectFire = false,
        MaxAmmo = 60,
        AddAmmo = 12,
    },
    [GetHashKey('weapon_rubberslug')] = {
        WeaponID = 'weapon_rubberslug',   
        AmmoType = 'AMMO_RUBBER_SHOTGUN',
        SelectFire = false,
        MaxAmmo = 40,
        AddAmmo = 20,
    },
    [GetHashKey('weapon_huntingrifle')] = {
        WeaponID = 'weapon_huntingrifle',   
        AmmoType = 'AMMO_SNIPER',
        SelectFire = false,
        MaxAmmo = 24,
        AddAmmo = 12,
    },
    [GetHashKey('weapon_empgun')] = {
        WeaponID = 'weapon_empgun',  
        AmmoType = 'AMMO_EMP',
        SelectFire = false,
        MaxAmmo = 5,
        AddAmmo = 3,
    },
    [GetHashKey('weapon_snowballlauncher')] = {
        WeaponID = 'weapon_snowballlauncher',  
        AmmoType = 'AMMO_SNOWBALLLAUNCHER',
        SelectFire = false,
        MaxAmmo = 15,
        AddAmmo = 3,
    },

    -- Melee
    [GetHashKey('weapon_flashlight')] = {
        WeaponID = 'weapon_flashlight',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.4,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_switchblade')] = {
        WeaponID = 'weapon_switchblade',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.2,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_gavel')] = {
        WeaponID = 'weapon_gavel',
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.2,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_shiv')] = {
        WeaponID = 'weapon_shiv',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.2,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_shoe')] = {
        WeaponID = 'weapon_shoe',
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_brick')] = {
        WeaponID = 'weapon_brick',
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_snowball')] = {
        WeaponID = 'weapon_snowball',
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.0,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_banana')] = {
        WeaponID = 'weapon_banana',
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_sledgeham')] = {
        WeaponID = 'weapon_sledgeham',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_katana')] = {
        WeaponID = 'weapon_katana',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_nightstick')] = {
        WeaponID = 'weapon_nightstick',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_crowbar')] = {
        WeaponID = 'weapon_crowbar',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_hammer')] = {
        WeaponID = 'weapon_hammer',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_machete')] = {
        WeaponID = 'weapon_machete',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_poolcue')] = {
        WeaponID = 'weapon_poolcue',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_wrench')] = {
        WeaponID = 'weapon_wrench',  
        AmmoType = 'AMMO_NONE',
        SelectFire = false,
        Modifier = 0.01,
        MaxAmmo = 0,
        AddAmmo = 0,
    },

    -- Explosive
    [GetHashKey('weapon_grenade')] = {
        WeaponID = 'weapon_grenade',  
        AmmoType = 'AMMO_FIRE',
        SelectFire = false,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
    [GetHashKey('weapon_stickybomb')] = {
        WeaponID = 'weapon_stickybomb',  
        AmmoType = 'AMMO_FIRE',
        SelectFire = false,
        MaxAmmo = 0,
        AddAmmo = 0,
    },
}