Config.Jobs = {
    ["fooddelivery"] = {
        Icon = "fas fa-utensils",
        Coords = vector3(-232.43, -915.5, 31.31),
        Heading = 342.21,
        JobId = "fooddelivery",
        JobName = "Voedsel Bezorger",
        PedModel = "s_m_m_linecook",
        Anim = { Dict = "missheistdockssetup1clipboard@base", Name = "base" },
        Props = {
            { Prop = 'prop_notepad_01', Bone = 18905, Placement = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
            { Prop = 'prop_pencil_01', Bone = 58866, Placement = { 0.11, -0.02, 0.001, -120.0, 0.0, 0.0 } },
        },
        BasePayment = 10,
        BaseIncreasement = { 1.0 },
        GroupSize = 1,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["fishing"] = {
        Icon = "fas fa-fish",
        Coords = vector3(-335.37, 6105.7, 30.45),
        Heading = 225.89,
        JobId = "fishing",
        JobName = "Vissen",
        PedModel = "cs_old_man1a",
        Anim = { Dict = "missheistdockssetup1clipboard@base", Name = "base" },
        Props = {
            { Prop = 'prop_notepad_01', Bone = 18905, Placement = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
            { Prop = 'prop_pencil_01', Bone = 58866, Placement = { 0.11, -0.02, 0.001, -120.0, 0.0, 0.0 } },
        },
        BasePayment = 375,
        BaseIncreasement = { 1.0, 0.9, 0.8, 0.7 },
        GroupSize = 4,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["chopshop"] = {
        Icon = "fas fa-car-crash",
        Coords = vector3(-274.82, 167.96, 77.93),
        Heading = 88.95,
        JobId = "chopshop",
        JobName = "Chop Shop",
        PedModel = "s_m_m_lathandy_01",
        Anim = {},
        Props = {},
        BasePayment = 0,
        GroupSize = 4,
        VPNRequired = true,
        OfferQueue = true,
    },
    ["sanitation"] = {
        Icon = "fas fa-trash-alt",
        Coords = vector3(-353.10, -1546.22, 26.8),
        Heading = 269.21,
        JobId = "sanitation",
        JobName = "Vuilnismedewerker",
        PedModel = "s_m_y_construct_01",
        Anim = { Dict = "missheistdockssetup1clipboard@base", Name = "base" },
        Props = {
            { Prop = 'prop_notepad_01', Bone = 18905, Placement = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
            { Prop = 'prop_pencil_01', Bone = 58866, Placement = { 0.11, -0.02, 0.001, -120.0, 0.0, 0.0 } },
        },
        BasePayment = 455,
        BaseIncreasement = { 1.0, 0.8, 0.6, 0.5 },
        GroupSize = 4,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["impound"] = {
        Icon = "fas fa-truck",
        Coords = vector3(1000.2, -2310.57, 29.57),
        Heading = 270.09,
        JobId = "impound",
        JobName = "Depot Medewerker",
        PedModel = "mp_m_waremech_01",
        Anim = { Dict = "missheistdockssetup1clipboard@base", Name = "base" },
        Props = {
            { Prop = 'prop_notepad_01', Bone = 18905, Placement = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
            { Prop = 'prop_pencil_01', Bone = 58866, Placement = { 0.11, -0.02, 0.001, -120.0, 0.0, 0.0 } },
        },
        BasePayment = 350,
        BaseIncreasement = { 1.0 },
        GroupSize = 1,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["houses"] = {
        Icon = "fas fa-house",
        Coords = vector3(-488.91, 299.03, 82.79),
        Heading = 357.75,
        JobId = "houses",
        JobName = "Schoonmaakbedrijf",
        PedModel = "a_m_m_og_boss_01",
        BasePayment = 0,
        GroupSize = 4,
        VPNRequired = true,
        OfferQueue = true,
    },
    ["oxy"] = {
        Icon = "fas fa-newspaper",
        Coords = vector3(-458.27, -2266.15, 7.52),
        Heading = 274.08,
        JobId = "oxy",
        JobName = "\"Kranten\" Verkoper",
        PedModel = "a_m_m_og_boss_01",
        BasePayment = 0,
        GroupSize = 2,
        VPNRequired = true,
        OfferQueue = true,
    },
    ["postop"] = {
        Icon = "fas fa-store-alt",
        Coords = vector3(929.99, -1249.48, 24.5),
        Heading = 32.94,
        JobId = "postop",
        JobName = "24/7 Logistiek",
        PedModel = "s_m_m_gentransport",
        BasePayment = 305,
        BaseIncreasement = { 1.0, 0.89 },
        GroupSize = 2,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["boosting"] = {
        Icon = "",
        Coords = vector3(0.0, 0.0, -100.0),
        Heading = 0.0,
        JobId = "boosting",
        JobName = "Boosting",
        PedModel = "s_m_m_postal_02",
        BasePayment = 0,
        GroupSize = 2,
        VPNRequired = true,
        OfferQueue = false,
        IgnoreQueue = true, -- Queue is handled by the boosting laptop.
        Hidden = true,
        PreventCancel = true, -- Cancel is handled by the boosting laptop.
    },
    ["construction"] = {
        Icon = "fas fa-user-hard-hat",
        Coords = vector3(1122.69, -1304.65, 33.72),
        Heading = 356.11,
        JobId = "construction",
        JobName = "Bouwvakker",
        PedModel = "s_m_y_construct_02",
        BasePayment = 365,
        BaseIncreasement = { 1.0, 0.93 },
        GroupSize = 2,
        VPNRequired = false,
        OfferQueue = false,
    },
    ["weedrun"] = {
        Icon = "fas fa-user-hard-hat",
        Coords = vector3(1233.21, 2737.31, 37.01),
        Heading = 273.26,
        JobId = "weedrun",
        JobName = "Roadman Delivery",
        PedModel = "a_m_y_eastsa_01",
        BasePayment = 0,
        GroupSize = 1,
        VPNRequired = true,
        OfferQueue = true,
        Hidden = true,
    },
}